int n1;
int n2;
int soma;
Console.WriteLine("Digite o primeiro número");
n1 = int.Parse(Console.ReadLine());
Console.WriteLine("Digite o segundo número");
n2 = int.Parse(Console.ReadLine());
soma = n1 + n2;
Console.WriteLine("A Soma dos números são:");
Console.WriteLine(soma);
Console.ReadKey();